language: php
php:
  - 5.5
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - php: 7.0
before_install:
  - curl -s https://get.webino.org/support/travis/before-install | sudo -E sh
install:
  - curl -s https://get.webino.org/support/travis/install | sh
before_script:
  - curl -s https://get.webino.org/support/travis/before-script | sh
script:
  - curl -s https://get.webino.org/support/travis/script | sh
after_success:
  - curl -s https://get.webino.org/support/travis/after-success | sh
env:
  global:
    - URI=http://localhost:8000/
    - BROWSER=chrome
    - GH_REF=github.com/webino/WebinoCanonicalRedirect
    - secure: dgJ03wF/YelV7+84tPqsyghdHWYDNV4QQDsGmCoOBbpMsOVTp+KCfaER0hTpYLqBed+N5ukQDBEXQFMrzEPC7C7njW1DY+WgIxHOGOzdHqlN2ZlIG/BbRTA4Tjz1+LJAlZRHVnwGhYW8y5bdzayRVWdaOmxQ/smlf+bgdjUeBEo=
