<?php
/**
 * Webino (http://webino.sk)
 *
 * @link        https://github.com/webino/WebinoCanonicalRedirect for the canonical source repository
 * @copyright   Copyright (c) 2014-2017 Webino, s. r. o. (http://webino.sk)
 * @author      Peter Bačinský <peter@bacinsky.sk>
 * @license     BSD-3-Clause
 */

namespace WebinoCanonicalRedirect\Factory;

use WebinoCanonicalRedirect\Uri\Canonicalizer;
use Zend\Http\PhpEnvironment\Request;
use Zend\ServiceManager\ServiceManager;
use Zend\Uri\Uri;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-06 at 17:33:29.
 */
class CanonicalizerFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CanonicalizerFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CanonicalizerFactory;
    }

    /**
     * @covers WebinoCanonicalRedirect\Factory\CanonicalizerFactory::createService
     */
    public function testCreateService()
    {
        $request  = $this->getMock(Request::class);
        $services = $this->getMock(ServiceManager::class);

        $services->expects($this->once())
            ->method('get')
            ->with('Request')
            ->will($this->returnValue($request));

        $request->expects($this->once())
            ->method('getUri')
            ->will($this->returnValue($this->getMock(Uri::class)));

        $request->expects($this->once())
            ->method('getBaseUrl')
            ->will($this->returnValue(''));

        $canonicalizer = $this->object->createService($services);
        $this->assertInstanceOf(Canonicalizer::class, $canonicalizer);
    }
}
