<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'WebinoCanonicalRedirect\Module'        => __DIR__ . '/Module.php',
  'WebinoCanonicalRedirect\Uri\Normalize' => __DIR__ . '/Uri/Normalize.php',
);
