<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'WebinoCanonicalRedirect\Module'                       => __DIR__ . '/Module.php',
  'WebinoCanonicalRedirect\Uri\Canonicalizer'            => __DIR__ . '/Uri/Canonicalizer.php',
  'WebinoCanonicalRedirect\Factory\ModuleOptionsFactory' => __DIR__ . '/Factory/ModuleOptionsFactory.php',
  'WebinoCanonicalRedirect\Factory\CanonicalizerFactory' => __DIR__ . '/Factory/CanonicalizerFactory.php',
  'WebinoCanonicalRedirect\Options\ModuleOptions'        => __DIR__ . '/Options/ModuleOptions.php',
);
