<?php

namespace WebinoCanonicalRedirect\Uri;

/**
 * Test class for Normalize.
 * Generated by PHPUnit on 2013-02-16 at 12:32:36.
 */
class NormalizeTest
        extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Normalize
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $uri = $this->getMock('\Zend\Uri\Uri');

        $this->object = new Normalize($uri);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WebinoCanonicalRedirect\Uri\Normalize::getIsNormalized
     * @todo Implement testGetIsNormalized().
     */
    public function testGetIsNormalized()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoCanonicalRedirect\Uri\Normalize::www
     * @todo Implement testWww().
     */
    public function testWww()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoCanonicalRedirect\Uri\Normalize::trailingSlash
     * @todo Implement testTrailingSlash().
     */
    public function testTrailingSlash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoCanonicalRedirect\Uri\Normalize::toString
     * @todo Implement testToString().
     */
    public function testToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoCanonicalRedirect\Uri\Normalize::__toString
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
